### ISSUE TITLE
Updates April 9th

### ISSUE THREAD

**Issue by ontehfritz** [nasajoey/Java-API-to-mtgdb#1]
Fields being updated: 
Card: [token] boolean - indicates if the card is token or not
CardSet - [total] integer - total cards available in set

Two new methods: 

/sets/[id]/cards/random - Gets a random card from a set
/cards/random - Get a random card

**Comment by alotau** [comment]
How does the boolean come across in the JSON?  Will I get in trouble treating as an int or is it actually a 'true'/'false' value?

**Comment by alotau** [comment]
I'll wait until this is 'live' from your server so I can see samples before updating.

**Comment by ontehfritz** [comment]
"token":true thats the JSON, with c# using JSON.net all primitives are easily de-serializable, I imagine  in java it probably won't be difficult

**Comment by alotau** [comment]
Updated.
