### ISSUE TITLE
FYI: Someone trying to use the Jar on AppSpot

### ISSUE THREAD

**Issue by ontehfritz** [nasajoey/Java-API-to-mtgdb#10]
https://answers.yahoo.com/question/index?qid=20140610073759AAq2nYN

**Comment by alotau** [comment]
Not sure if I can help much with that.  It should just be a classpath problem and making sure it gets uploaded appropriately with his project.  Maybe I'll leave an answer for him, but this is not so much a problem with the API.

Anyway, thanks for the heads-up on the question.
