### ISSUE TITLE
Card.getHiResImageUrl() doesn't work

### ISSUE THREAD

**Issue by Afterstone** [nasajoey/Java-API-to-mtgdb#14]
Hi!

I can't get Card.getHiResImageUrl() to work. It returns image URLs on the form https://api.mtgdb.info/content/hi_res_card_images/207890.jpeg, but they need to be https://api.mtgdb.info/content/hi_res_card_images/207890.jpg.

**Comment by alotau** [comment]
Applied your fix.  Let me know if it still has issues.  Thanks!
