### ISSUE TITLE
Create github page for documentation and download

### ISSUE THREAD

**Issue by ontehfritz** [nasajoey/Java-API-to-mtgdb#6]
This will save us the time of having to upload and update the client and you can stick the documentation on there.

**Comment by alotau** [comment]
Got a page up.  Will send you the links:

Site:   http://alotau.github.io/Java-API-to-mtgdb/
Direct jar download:  http://alotau.github.io/Java-API-to-mtgdb/mtgdb.info_java_api.jar
Javadoc:  http://alotau.github.io/Java-API-to-mtgdb/doc

**Comment by ontehfritz** [comment]
:+1:
